import React from 'react'
import { JobsPage, ResumesPage } from '@/pages/Recruiter'
import { ProfilePage, ResultsPage } from '@/pages/shared'
import { AdminOverview } from './AdminOverview'
import { LogsPage } from './LogsPage'
import { SkillsPage } from './SkillsPage'
import { UsersPage } from './UsersPage'

export function AdminWorkspace({ current, token, session, onSession, notify, onNavigate }) {
  if (current === 'overview') return <AdminOverview token={token} onNavigate={onNavigate} />
  if (current === 'users') return <UsersPage token={token} currentUser={session.user} notify={notify} />
  if (current === 'resumes') return <ResumesPage token={token} notify={notify} admin />
  if (current === 'jobs') return <JobsPage token={token} notify={notify} admin />
  if (current === 'results') return <ResultsPage token={token} endpoint="/api/admin/results" title="System analysis results" subtitle="Inspect every ATS evaluation generated by the platform." />
  if (current === 'skills') return <SkillsPage token={token} notify={notify} />
  if (current === 'logs') return <LogsPage token={token} />
  return <ProfilePage token={token} user={session.user} onSession={onSession} notify={notify} />
}

