import React, { useEffect, useState } from 'react'
import { getAdminDashboard, listLogs, listResults } from '@/api'
import { ActivityList, Button, Icon, OverviewHero, Panel, Spinner, StatCard } from '@/components'
import { pageRecords } from '@/utils'

export function AdminOverview({ token, onNavigate }) {
  const [state, setState] = useState({ loading: true, stats: {}, logs: [], results: [], error: '' })
  useEffect(() => {
    Promise.all([getAdminDashboard(token), listLogs({ token, limit: 6 }), listResults({ token, limit: 5, admin: true })]).then(([stats, logs, results]) => setState({ loading: false, stats, logs: pageRecords(logs), results: pageRecords(results), error: '' })).catch((err) => setState((s) => ({ ...s, loading: false, error: err.message })))
  }, [token])
  const stats = state.stats || {}
  const total = Number(stats.users || 0) + Number(stats.resumes || 0) + Number(stats.job_descriptions || 0) + Number(stats.results || 0)
  const segments = [stats.users, stats.resumes, stats.job_descriptions, stats.results].map((value) => total ? Math.round(Number(value || 0) / total * 100) : 0)
  return <><OverviewHero eyebrow="Administration console" title="Operational visibility across the full platform." text="Monitor adoption, content, AI analysis output, and audit events while managing system records securely." action={<Button icon="users" onClick={() => onNavigate('users')}>Manage users</Button>} />{state.error && <div className="inline-error"><Icon name="warning" />{state.error}</div>}<div className="stats-grid admin-stats"><StatCard label="Registered users" value={stats.users} icon="users" tone="blue" helper="All roles" /><StatCard label="Stored resumes" value={stats.resumes} icon="resume" tone="purple" helper="Candidate and recruiter uploads" /><StatCard label="Job descriptions" value={stats.job_descriptions} icon="jobs" tone="orange" helper="Hiring criteria" /><StatCard label="Analysis results" value={stats.results} icon="results" tone="green" helper="Completed evaluations" /><StatCard label="Audit events" value={stats.logs} icon="logs" tone="slate" helper="Tracked system actions" /></div><div className="admin-dashboard-grid"><Panel title="Platform distribution" subtitle="Relative volume across core records"><div className="distribution-chart"><div className="donut" style={{ '--p1': `${segments[0]}%`, '--p2': `${segments[0] + segments[1]}%`, '--p3': `${segments[0] + segments[1] + segments[2]}%` }}><div><strong>{total.toLocaleString()}</strong><span>Total records</span></div></div><div className="chart-legend"><div><i className="chart-blue" /><span>Users</span><strong>{stats.users || 0}</strong></div><div><i className="chart-purple" /><span>Resumes</span><strong>{stats.resumes || 0}</strong></div><div><i className="chart-orange" /><span>Job descriptions</span><strong>{stats.job_descriptions || 0}</strong></div><div><i className="chart-green" /><span>Results</span><strong>{stats.results || 0}</strong></div></div></div></Panel><Panel title="Recent audit activity" subtitle="Latest system events" actions={<Button variant="ghost" size="small" onClick={() => onNavigate('logs')}>Open logs <Icon name="arrow" size={14} /></Button>}>{state.loading ? <Spinner /> : <ActivityList rows={state.logs} type="log" />}</Panel><Panel title="Latest analysis results" subtitle="Recently completed ATS evaluations" actions={<Button variant="ghost" size="small" onClick={() => onNavigate('results')}>View results <Icon name="arrow" size={14} /></Button>}>{state.loading ? <Spinner /> : <ActivityList rows={state.results} />}</Panel></div></>
}

